name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: build-and-test-${{matrix.rid}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, win-arm64,linux-x64, linux-arm64, linux-arm, osx-x64]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --runtime ${{ matrix.rid }} -p:PublishTrimmed -p:DebugType=None -p:DebugSymbols=false --self-contained -p:PublishSingleFile=true -o publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lazyandrew-${{ matrix.rid }}
        path: publish/lazyandrew**
        if-no-files-found: error

